[project]
name = "litestar-parameter-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "litestar[standard]>=2.14.0",
]
